name: Build new image
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Stage name
    name: build binary
    # This job runs on Linux
    runs-on: ubuntu-latest
    # Step build
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: "1.13"
    - run: |
        cd src
        make test
    - name: Notify slack fail
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Unit test failed"

    - name: Build new binary
      run: |
        cd src
        make build

    - name: Notify slack fail
      if: failure()
      uses: rtCamp/action-slack-notify@master
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_MESSAGE: "Build failed"


    - name: Create Pull Request
      id: cpr
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.PAT }}
        commit-message: Update report
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        signoff: false
        branch: master
        delete-branch: true
        title: '[Example] Update report'
